FROM public.ecr.aws/lambda/python:3.9

ENV AM_I_IN_A_DOCKER_CONTAINER=True

RUN pip install -U pip


COPY requirements.txt ./
COPY [ "app.py", "xgb_reg.pkl", "./" ]

RUN pip install -r requirements.txt

CMD ["app.handler"]